apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-demo
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 387637752303.dkr.ecr.us-east-1.amazonaws.com/demo-test1:27
          ports:
            - name: frontend
              containerPort: 5000