apiVersion: v1
kind: Service
metadata:
  name: frontend-service-demo
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
